### ISSUE TITLE
挑戦6で効力11が考慮される

### ISSUE THREAD

**Issue by lemoncmd** [to-omer/newincrementalgame-simulator#1]
時間加速器は購入できないので時間加速器2の購入数は考慮外になるべきですよね…？違ってたらごめんなさい

**Comment by to-omer** [comment]
これは挑戦タブのことですか？
その場合、？タブに大体書いてありますが、どの挑戦でも効力の組み合わせとして効力3,4,7,8,11,12,14の極大集合（それ以上他の効力を選択できない組み合わせ）を探索しているので、不要な効力が入ることがあります。
特別処理は今のところやっていません。

**Comment by lemoncmd** [comment]
というのも、挑戦356を見ると効力が3,4,7,8,11,12となっていて、11,12は無意味なはずでしかも14が選ばれてないんですよ。

**Comment by to-omer** [comment]
現在の実装では、必要時間が同じなら一番初めの候補を出力するようになっているので、挑戦5が有効なために 1tick も差が出ないほど効力14が弱いということだと思います。
挑戦3456とかを見ると効力14が選ばれているはずです。
